apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loan-prediction-api
spec:
  project: default
  source:
    repoURL: https://github.com/kellybourbon2/loan-prediction-approval-deployment.git
    targetRevision: main
    path: deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: user-kbourbon
  syncPolicy:
    automated:
      selfHeal: true